version: '3.8'

services:
  crate:
    build:
      context: .
      dockerfile: Crate.Dockerfile
    container_name: code-crate
    ports:
      - '8080:8080'
    environment:
      - PASSWORD=dev
    volumes:
      - ./workspace:/home/coder/workspace
